// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/tts.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TTSRequest contains the text and language for TTS
type TTSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	LanguageCode  string                 `protobuf:"bytes,2,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`  // e.g., "en-US", "fr-FR", "es-ES"
	ForceRefresh  bool                   `protobuf:"varint,3,opt,name=force_refresh,json=forceRefresh,proto3" json:"force_refresh,omitempty"` // if true, bypass cache and refetch from Azure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTSRequest) Reset() {
	*x = TTSRequest{}
	mi := &file_proto_tts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTSRequest) ProtoMessage() {}

func (x *TTSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTSRequest.ProtoReflect.Descriptor instead.
func (*TTSRequest) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{0}
}

func (x *TTSRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TTSRequest) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *TTSRequest) GetForceRefresh() bool {
	if x != nil {
		return x.ForceRefresh
	}
	return false
}

// TTSResponse contains the audio data and metadata
type TTSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cached        bool                   `protobuf:"varint,1,opt,name=cached,proto3" json:"cached,omitempty"`                        // whether audio was retrieved from cache
	AudioData     []byte                 `protobuf:"bytes,2,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`  // MP3 audio data
	CacheKey      string                 `protobuf:"bytes,3,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"`     // hash used as cache key
	AudioSize     int64                  `protobuf:"varint,4,opt,name=audio_size,json=audioSize,proto3" json:"audio_size,omitempty"` // size of audio data in bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTSResponse) Reset() {
	*x = TTSResponse{}
	mi := &file_proto_tts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTSResponse) ProtoMessage() {}

func (x *TTSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTSResponse.ProtoReflect.Descriptor instead.
func (*TTSResponse) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{1}
}

func (x *TTSResponse) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

func (x *TTSResponse) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *TTSResponse) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

func (x *TTSResponse) GetAudioSize() int64 {
	if x != nil {
		return x.AudioSize
	}
	return 0
}

// PlayResponse indicates success/failure of playback
type PlayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	WasCached     bool                   `protobuf:"varint,3,opt,name=was_cached,json=wasCached,proto3" json:"was_cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayResponse) Reset() {
	*x = PlayResponse{}
	mi := &file_proto_tts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayResponse) ProtoMessage() {}

func (x *PlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayResponse.ProtoReflect.Descriptor instead.
func (*PlayResponse) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{2}
}

func (x *PlayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlayResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PlayResponse) GetWasCached() bool {
	if x != nil {
		return x.WasCached
	}
	return false
}

// DeleteResponse indicates success/failure of deletion
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CacheKey      string                 `protobuf:"bytes,3,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_tts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteResponse) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

var File_proto_tts_proto protoreflect.FileDescriptor

const file_proto_tts_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/tts.proto\x12\x03tts\"j\n" +
	"\n" +
	"TTSRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12#\n" +
	"\rlanguage_code\x18\x02 \x01(\tR\flanguageCode\x12#\n" +
	"\rforce_refresh\x18\x03 \x01(\bR\fforceRefresh\"\x80\x01\n" +
	"\vTTSResponse\x12\x16\n" +
	"\x06cached\x18\x01 \x01(\bR\x06cached\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x02 \x01(\fR\taudioData\x12\x1b\n" +
	"\tcache_key\x18\x03 \x01(\tR\bcacheKey\x12\x1d\n" +
	"\n" +
	"audio_size\x18\x04 \x01(\x03R\taudioSize\"a\n" +
	"\fPlayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"was_cached\x18\x03 \x01(\bR\twasCached\"a\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tcache_key\x18\x03 \x01(\tR\bcacheKey2\xd5\x01\n" +
	"\n" +
	"TTSService\x12-\n" +
	"\bFetchTTS\x12\x0f.tts.TTSRequest\x1a\x10.tts.TTSResponse\x12-\n" +
	"\aPlayTTS\x12\x0f.tts.TTSRequest\x1a\x11.tts.PlayResponse\x123\n" +
	"\x0eGetCachedAudio\x12\x0f.tts.TTSRequest\x1a\x10.tts.TTSResponse\x124\n" +
	"\fDeleteCached\x12\x0f.tts.TTSRequest\x1a\x13.tts.DeleteResponseB!Z\x1fcom.biesnecker/tts-daemon/protob\x06proto3"

var (
	file_proto_tts_proto_rawDescOnce sync.Once
	file_proto_tts_proto_rawDescData []byte
)

func file_proto_tts_proto_rawDescGZIP() []byte {
	file_proto_tts_proto_rawDescOnce.Do(func() {
		file_proto_tts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tts_proto_rawDesc), len(file_proto_tts_proto_rawDesc)))
	})
	return file_proto_tts_proto_rawDescData
}

var file_proto_tts_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_tts_proto_goTypes = []any{
	(*TTSRequest)(nil),     // 0: tts.TTSRequest
	(*TTSResponse)(nil),    // 1: tts.TTSResponse
	(*PlayResponse)(nil),   // 2: tts.PlayResponse
	(*DeleteResponse)(nil), // 3: tts.DeleteResponse
}
var file_proto_tts_proto_depIdxs = []int32{
	0, // 0: tts.TTSService.FetchTTS:input_type -> tts.TTSRequest
	0, // 1: tts.TTSService.PlayTTS:input_type -> tts.TTSRequest
	0, // 2: tts.TTSService.GetCachedAudio:input_type -> tts.TTSRequest
	0, // 3: tts.TTSService.DeleteCached:input_type -> tts.TTSRequest
	1, // 4: tts.TTSService.FetchTTS:output_type -> tts.TTSResponse
	2, // 5: tts.TTSService.PlayTTS:output_type -> tts.PlayResponse
	1, // 6: tts.TTSService.GetCachedAudio:output_type -> tts.TTSResponse
	3, // 7: tts.TTSService.DeleteCached:output_type -> tts.DeleteResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tts_proto_init() }
func file_proto_tts_proto_init() {
	if File_proto_tts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tts_proto_rawDesc), len(file_proto_tts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tts_proto_goTypes,
		DependencyIndexes: file_proto_tts_proto_depIdxs,
		MessageInfos:      file_proto_tts_proto_msgTypes,
	}.Build()
	File_proto_tts_proto = out.File
	file_proto_tts_proto_goTypes = nil
	file_proto_tts_proto_depIdxs = nil
}
