// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/tts.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TTSService_FetchTTS_FullMethodName       = "/tts.TTSService/FetchTTS"
	TTSService_BulkFetchTTS_FullMethodName   = "/tts.TTSService/BulkFetchTTS"
	TTSService_PlayTTS_FullMethodName        = "/tts.TTSService/PlayTTS"
	TTSService_GetCachedAudio_FullMethodName = "/tts.TTSService/GetCachedAudio"
	TTSService_DeleteCached_FullMethodName   = "/tts.TTSService/DeleteCached"
)

// TTSServiceClient is the client API for TTSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TTSService handles text-to-speech requests
type TTSServiceClient interface {
	// FetchTTS fetches and caches audio for the given text
	FetchTTS(ctx context.Context, in *TTSRequest, opts ...grpc.CallOption) (*TTSResponse, error)
	// BulkFetchTTS fetches and caches audio for multiple texts concurrently
	BulkFetchTTS(ctx context.Context, in *BulkTTSRequest, opts ...grpc.CallOption) (*BulkTTSResponse, error)
	// PlayTTS fetches (if needed), caches, and plays audio for the given text
	PlayTTS(ctx context.Context, in *TTSRequest, opts ...grpc.CallOption) (*PlayResponse, error)
	// GetCachedAudio retrieves audio from cache without fetching
	GetCachedAudio(ctx context.Context, in *TTSRequest, opts ...grpc.CallOption) (*TTSResponse, error)
	// DeleteCached removes audio from cache
	DeleteCached(ctx context.Context, in *TTSRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type tTSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTTSServiceClient(cc grpc.ClientConnInterface) TTSServiceClient {
	return &tTSServiceClient{cc}
}

func (c *tTSServiceClient) FetchTTS(ctx context.Context, in *TTSRequest, opts ...grpc.CallOption) (*TTSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TTSResponse)
	err := c.cc.Invoke(ctx, TTSService_FetchTTS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tTSServiceClient) BulkFetchTTS(ctx context.Context, in *BulkTTSRequest, opts ...grpc.CallOption) (*BulkTTSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkTTSResponse)
	err := c.cc.Invoke(ctx, TTSService_BulkFetchTTS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tTSServiceClient) PlayTTS(ctx context.Context, in *TTSRequest, opts ...grpc.CallOption) (*PlayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayResponse)
	err := c.cc.Invoke(ctx, TTSService_PlayTTS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tTSServiceClient) GetCachedAudio(ctx context.Context, in *TTSRequest, opts ...grpc.CallOption) (*TTSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TTSResponse)
	err := c.cc.Invoke(ctx, TTSService_GetCachedAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tTSServiceClient) DeleteCached(ctx context.Context, in *TTSRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, TTSService_DeleteCached_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TTSServiceServer is the server API for TTSService service.
// All implementations must embed UnimplementedTTSServiceServer
// for forward compatibility.
//
// TTSService handles text-to-speech requests
type TTSServiceServer interface {
	// FetchTTS fetches and caches audio for the given text
	FetchTTS(context.Context, *TTSRequest) (*TTSResponse, error)
	// BulkFetchTTS fetches and caches audio for multiple texts concurrently
	BulkFetchTTS(context.Context, *BulkTTSRequest) (*BulkTTSResponse, error)
	// PlayTTS fetches (if needed), caches, and plays audio for the given text
	PlayTTS(context.Context, *TTSRequest) (*PlayResponse, error)
	// GetCachedAudio retrieves audio from cache without fetching
	GetCachedAudio(context.Context, *TTSRequest) (*TTSResponse, error)
	// DeleteCached removes audio from cache
	DeleteCached(context.Context, *TTSRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedTTSServiceServer()
}

// UnimplementedTTSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTTSServiceServer struct{}

func (UnimplementedTTSServiceServer) FetchTTS(context.Context, *TTSRequest) (*TTSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchTTS not implemented")
}
func (UnimplementedTTSServiceServer) BulkFetchTTS(context.Context, *BulkTTSRequest) (*BulkTTSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkFetchTTS not implemented")
}
func (UnimplementedTTSServiceServer) PlayTTS(context.Context, *TTSRequest) (*PlayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayTTS not implemented")
}
func (UnimplementedTTSServiceServer) GetCachedAudio(context.Context, *TTSRequest) (*TTSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCachedAudio not implemented")
}
func (UnimplementedTTSServiceServer) DeleteCached(context.Context, *TTSRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCached not implemented")
}
func (UnimplementedTTSServiceServer) mustEmbedUnimplementedTTSServiceServer() {}
func (UnimplementedTTSServiceServer) testEmbeddedByValue()                    {}

// UnsafeTTSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TTSServiceServer will
// result in compilation errors.
type UnsafeTTSServiceServer interface {
	mustEmbedUnimplementedTTSServiceServer()
}

func RegisterTTSServiceServer(s grpc.ServiceRegistrar, srv TTSServiceServer) {
	// If the following call pancis, it indicates UnimplementedTTSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TTSService_ServiceDesc, srv)
}

func _TTSService_FetchTTS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TTSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTSServiceServer).FetchTTS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TTSService_FetchTTS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTSServiceServer).FetchTTS(ctx, req.(*TTSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TTSService_BulkFetchTTS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkTTSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTSServiceServer).BulkFetchTTS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TTSService_BulkFetchTTS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTSServiceServer).BulkFetchTTS(ctx, req.(*BulkTTSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TTSService_PlayTTS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TTSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTSServiceServer).PlayTTS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TTSService_PlayTTS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTSServiceServer).PlayTTS(ctx, req.(*TTSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TTSService_GetCachedAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TTSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTSServiceServer).GetCachedAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TTSService_GetCachedAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTSServiceServer).GetCachedAudio(ctx, req.(*TTSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TTSService_DeleteCached_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TTSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTSServiceServer).DeleteCached(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TTSService_DeleteCached_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTSServiceServer).DeleteCached(ctx, req.(*TTSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TTSService_ServiceDesc is the grpc.ServiceDesc for TTSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TTSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tts.TTSService",
	HandlerType: (*TTSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchTTS",
			Handler:    _TTSService_FetchTTS_Handler,
		},
		{
			MethodName: "BulkFetchTTS",
			Handler:    _TTSService_BulkFetchTTS_Handler,
		},
		{
			MethodName: "PlayTTS",
			Handler:    _TTSService_PlayTTS_Handler,
		},
		{
			MethodName: "GetCachedAudio",
			Handler:    _TTSService_GetCachedAudio_Handler,
		},
		{
			MethodName: "DeleteCached",
			Handler:    _TTSService_DeleteCached_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tts.proto",
}
